version: '2.1'
orbs:
  gh: circleci/github-cli@2.6
jobs:
  tag-and-release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Set up SSH keys
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - gh/install
      - run:
          name: Generate and create tag
          command: |
            DATE=$(date +'%Y%m%d')

            # Check if there are any tags for today (including cases with and without suffix)
            BASE_TAG="v$DATE"
            ALL_TAGS=$(git tag -l "$BASE_TAG*" | sort -V)

            if [ -z "$ALL_TAGS" ]; then
              # No tags for today, create the first tag
              NEW_TAG="$BASE_TAG"
            else
              # Tags already exist, get the latest tag
              LATEST_TAG=$(echo "$ALL_TAGS" | tail -n 1)
              if [[ "$LATEST_TAG" == "$BASE_TAG" ]]; then
                # If the latest tag has no suffix, use .1
                NEW_TAG="${BASE_TAG}.1"
              else
                # Extract the suffix number and increment it by 1
                COUNTER=$(echo "$LATEST_TAG" | awk -F'.' '{print $NF}')
                NEXT_COUNTER=$((COUNTER + 1))
                NEW_TAG="${BASE_TAG}.$NEXT_COUNTER"
              fi
            fi

            echo "Generated new tag: $NEW_TAG"
            echo "export NEW_TAG=$NEW_TAG" >> $BASH_ENV

            # Create and push tag
            git tag $NEW_TAG
            git push origin $NEW_TAG
      - run:
          name: Create GitHub Release
          command: |
            gh release create $NEW_TAG \
              --title $NEW_TAG \
              --generate-notes
workflows:
  use-my-orb:
    jobs:
      - tag-and-release
